# Generated by Django 5.1.15 on 2026-10-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSuccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='只取年月（统一存为该月 1 日）；含当月', verbose_name='更名生效月份')),
                ('predecessor_title_snapshot', models.CharField(help_text='建立关系时的原刊名，审计/重放时不再依赖 Title 现值', max_length=255, verbose_name='前身刊名快照')),
                ('predecessor_issn_snapshot', models.CharField(blank=True, max_length=9, verbose_name='前身ISSN快照')),
                ('state', models.CharField(choices=[('active', '生效中'), ('superseded', '已被新版本纠正'), ('revoked', '已撤销')], default='active', max_length=12)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoked_reason', models.CharField(blank=True, max_length=255, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successions_out', to='serials.title')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successions_in', to='serials.title')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='纠正本版本的新版本行', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='serials.titlesuccession')),
            ],
            options={
                'verbose_name': '刊名沿革',
                'ordering': ['effective_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '建立沿革'), ('correct', '纠正沿革'), ('revoke', '撤销沿革')], max_length=10)),
                ('effective_month', models.DateField(verbose_name='事件时的生效月份')),
                ('predecessor_title_snapshot', models.CharField(max_length=255, verbose_name='前身刊名快照')),
                ('predecessor_issn_snapshot', models.CharField(blank=True, max_length=9, verbose_name='前身ISSN快照')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='succession_audits', to='serials.title')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_succession_audits', to='serials.title')),
                ('new_succession', models.ForeignKey(blank=True, help_text='纠正事件产生的新版本行', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='born_from_audits', to='serials.titlesuccession')),
                ('succession', models.ForeignKey(help_text='事件所针对的（旧）关系版本行', on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='serials.titlesuccession')),
            ],
            options={
                'verbose_name': '刊名沿革审计',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('predecessor',), name='uniq_active_successor_per_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.CheckConstraint(condition=models.Q(('effective_month__day', 1)), name='succession_effective_month_is_month_start'),
        ),
    ]
