# Generated by Django 5.1.15 on 2026-10-02 02:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSuccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='该月（含）起的新发行归后继刊名；统一按当月 1 日存储', verbose_name='更名生效月份')),
                ('predecessor_title_snapshot', models.CharField(max_length=255, verbose_name='原刊名快照')),
                ('predecessor_issn_snapshot', models.CharField(blank=True, max_length=9, verbose_name='原ISSN快照')),
                ('successor_title_snapshot', models.CharField(max_length=255, verbose_name='新刊名快照')),
                ('successor_issn_snapshot', models.CharField(blank=True, max_length=9, verbose_name='新ISSN快照')),
                ('effective_day', models.GeneratedField(db_persist=True, expression=django.db.models.functions.datetime.ExtractDay('effective_month'), output_field=models.PositiveSmallIntegerField())),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('version', models.PositiveIntegerField(default=1, help_text='同一对刊名第几次建立沿革；撤销后重走为新版本', verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successions_out', to='serials.title', verbose_name='原刊名')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successions_in', to='serials.title', verbose_name='后继刊名')),
            ],
            options={
                'verbose_name': '刊名沿革',
                'ordering': ['effective_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TitleSuccessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('establish', '建立'), ('revoke', '撤销')], max_length=10, verbose_name='动作')),
                ('version', models.PositiveIntegerField(verbose_name='沿革版本快照')),
                ('actor', models.CharField(blank=True, max_length=80, verbose_name='操作人')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因/说明')),
                ('payload', models.JSONField(default=dict, help_text='建立时记录生效月与刊名/ISSN 快照；撤销时记录撤销时刻', verbose_name='事件载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('succession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='serials.titlesuccession', verbose_name='沿革')),
            ],
            options={
                'verbose_name': '沿革审计事件',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('predecessor', 'successor'), name='succ_unique_active_pair'),
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('predecessor',), name='succ_unique_active_predecessor'),
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('successor',), name='succ_unique_active_successor'),
        ),
        migrations.AddConstraint(
            model_name='titlesuccession',
            constraint=models.CheckConstraint(condition=models.Q(('effective_day', 1)), name='succ_effective_month_is_first_day'),
        ),
    ]
